"""tasas montos en expedientes

Revision ID: 153c64bd7841
Revises: f2d248f2e5f5
Create Date: 2025-08-16 15:51:36.123092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153c64bd7841'
down_revision = 'f2d248f2e5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tasa_sellado_monto', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tasa_visado_electrica_monto', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tasa_visado_salubridad_monto', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tasa_visado_gas_monto', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tasa_visado_electromecanica_monto', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_column('tasa_visado_electromecanica_monto')
        batch_op.drop_column('tasa_visado_gas_monto')
        batch_op.drop_column('tasa_visado_salubridad_monto')
        batch_op.drop_column('tasa_visado_electrica_monto')
        batch_op.drop_column('tasa_sellado_monto')

    # ### end Alembic commands ###
