"""agregar campos gop scraper

Revision ID: 23cda892bbac
Revises: 589829ad4c3f
Create Date: 2025-08-16 22:29:14.047080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23cda892bbac'
down_revision = '589829ad4c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gop_bandeja_actual', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('gop_usuario_asignado', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('gop_estado', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gop_fecha_entrada', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gop_ultima_sincronizacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_column('gop_ultima_sincronizacion')
        batch_op.drop_column('gop_fecha_entrada')
        batch_op.drop_column('gop_estado')
        batch_op.drop_column('gop_usuario_asignado')
        batch_op.drop_column('gop_bandeja_actual')

    # ### end Alembic commands ###
