"""agregar campo gop_fecha_en_bandeja

Revision ID: 2e79b8d3e248
Revises: 23cda892bbac
Create Date: 2025-08-18 00:36:30.064676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e79b8d3e248'
down_revision = '23cda892bbac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gop_fecha_en_bandeja', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_column('gop_fecha_en_bandeja')

    # ### end Alembic commands ###
