"""Agregar partida_inmobiliaria a Expediente

Revision ID: 3ed2423e8c59
Revises: f4fef4296ff4
Create Date: 2025-08-16 21:35:49.970229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed2423e8c59'
down_revision = 'f4fef4296ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partida_inmobiliaria', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_column('partida_inmobiliaria')

    # ### end Alembic commands ###
