"""add partida_inmobiliaria y nro_expediente_municipal

Revision ID: 589829ad4c3f
Revises: 3ed2423e8c59
Create Date: 2025-08-16 22:07:12.580184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589829ad4c3f'
down_revision = '3ed2423e8c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nro_expediente_municipal', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_column('nro_expediente_municipal')

    # ### end Alembic commands ###
