"""crear tabla profesionales adicionales

Revision ID: 726da3c6efaa
Revises: 8a7f7633500d
Create Date: 2025-08-20 21:51:35.394774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726da3c6efaa'
down_revision = '8a7f7633500d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profesionales_adicionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=False),
    sa.Column('nombre_profesional', sa.String(length=200), nullable=False),
    sa.Column('whatsapp_profesional', sa.String(length=50), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profesionales_adicionales')
    # ### end Alembic commands ###
