"""agregar profesion a profesionales adicionales

Revision ID: 8c141fd01438
Revises: 0bb974ae67c1
Create Date: 2025-08-23 11:24:04.464564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c141fd01438'
down_revision = '0bb974ae67c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesionales_adicionales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profesion', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesionales_adicionales', schema=None) as batch_op:
        batch_op.drop_column('profesion')

    # ### end Alembic commands ###
