"""Add profesion_texto to ProfesionalAdicional

Revision ID: 93cf33fea229
Revises: a72840f439da
Create Date: 2025-08-27 10:12:32.854403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93cf33fea229'
down_revision = 'a72840f439da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesionales_adicionales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profesion_texto', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesionales_adicionales', schema=None) as batch_op:
        batch_op.drop_column('profesion_texto')

    # ### end Alembic commands ###
