
# revision identifiers, used by Alembic.
revision = '94085cde3a3b'
down_revision = '96b6f5c4471c'
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94085cde3a3b'
down_revision = '96b6f5c4471c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('en_oficina_tecnica', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_column('en_oficina_tecnica')
    # ### end Alembic commands ###
