"""remover unique de nro_expediente_cpim

Revision ID: 96b6f5c4471c
Revises: 8c141fd01438
Create Date: 2025-08-23 11:56:57.434954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b6f5c4471c'
down_revision = '8c141fd01438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('expedientes_nro_expediente_cpim_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('expedientes_nro_expediente_cpim_key'), ['nro_expediente_cpim'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
