"""Add profesion_texto to profesionales_adicionales

Revision ID: a72840f439da
Revises: ee67e938d0f3
Create Date: 2025-08-27 10:06:34.616338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72840f439da'
down_revision = 'ee67e938d0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profesion_texto', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivos', schema=None) as batch_op:
        batch_op.drop_column('profesion_texto')

    # ### end Alembic commands ###
