"""agregar campos para bandejas específicas CPIM IMLAUER ONETTO PROFESIONAL

Revision ID: bd5ebec42d09
Revises: d368f14d10e5
Create Date: 2025-08-19 01:22:38.040657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5ebec42d09'
down_revision = 'd368f14d10e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bandeja_cpim_nombre', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bandeja_cpim_usuario', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bandeja_cpim_fecha', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('bandeja_cpim_sincronizacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bandeja_imlauer_nombre', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bandeja_imlauer_usuario', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bandeja_imlauer_fecha', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('bandeja_imlauer_sincronizacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bandeja_onetto_nombre', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bandeja_onetto_usuario', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bandeja_onetto_fecha', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('bandeja_onetto_sincronizacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bandeja_profesional_nombre', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bandeja_profesional_usuario', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bandeja_profesional_fecha', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('bandeja_profesional_sincronizacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_column('bandeja_profesional_sincronizacion')
        batch_op.drop_column('bandeja_profesional_fecha')
        batch_op.drop_column('bandeja_profesional_usuario')
        batch_op.drop_column('bandeja_profesional_nombre')
        batch_op.drop_column('bandeja_onetto_sincronizacion')
        batch_op.drop_column('bandeja_onetto_fecha')
        batch_op.drop_column('bandeja_onetto_usuario')
        batch_op.drop_column('bandeja_onetto_nombre')
        batch_op.drop_column('bandeja_imlauer_sincronizacion')
        batch_op.drop_column('bandeja_imlauer_fecha')
        batch_op.drop_column('bandeja_imlauer_usuario')
        batch_op.drop_column('bandeja_imlauer_nombre')
        batch_op.drop_column('bandeja_cpim_sincronizacion')
        batch_op.drop_column('bandeja_cpim_fecha')
        batch_op.drop_column('bandeja_cpim_usuario')
        batch_op.drop_column('bandeja_cpim_nombre')

    # ### end Alembic commands ###

