"""agregar fecha_finalizado a expedientes

Revision ID: d368f14d10e5
Revises: bcc482466b9c
Create Date: 2025-08-18 22:40:32.417076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd368f14d10e5'
down_revision = 'bcc482466b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_finalizado', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_column('fecha_finalizado')

    # ### end Alembic commands ###
