"""crear tabla usuarios

Revision ID: ee67e938d0f3
Revises: 94085cde3a3b
Create Date: 2025-08-25 21:43:52.458923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee67e938d0f3'
down_revision = '94085cde3a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nro_expediente_cpim'])

    with op.batch_alter_table('profesionales_adicionales', schema=None) as batch_op:
        batch_op.drop_column('profesion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesionales_adicionales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profesion', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('usuarios')
    # ### end Alembic commands ###
