"""estados pago por defecto y selects

Revision ID: f4fef4296ff4
Revises: 153c64bd7841
Create Date: 2025-08-16 16:25:53.092349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fef4296ff4'
down_revision = '153c64bd7841'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("UPDATE expedientes SET estado_pago_sellado='pendiente' WHERE estado_pago_sellado IS NULL;")
    op.execute("UPDATE expedientes SET estado_pago_visado='pendiente' WHERE estado_pago_visado IS NULL;")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.alter_column('estado_pago_sellado',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('estado_pago_visado',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedientes', schema=None) as batch_op:
        batch_op.alter_column('estado_pago_visado',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('estado_pago_sellado',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
